### ISSUE TITLE
gulpfile tweak

### ISSUE THREAD

**Issue by georgecrawford** [tatlay/harmony#23]
I love the comments in the gulpfile to delineate sections, but this comment - https://github.com/tatlay/harmony/blob/master/gulpfile.js#L31 - is not in the right place.

**Comment by tombassrosenfeld** [comment]
Dunned it.

**Comment by Pete-Latham** [comment]
Closing

**Comment by georgecrawford** [comment]
@tombassrosenfeld you made a nice fix, but it wasn't the one I asked for I'm afraid! Let me know if you need clarification.

**Comment by Pete-Latham** [comment]
Moved the JS comment to below the 'styles' task definition
